const mockProducts = [
  {
    product_name: "Laptop Dell XPS 15",
    category: "Electronics",
    unit_price: 1599.99,
    stock_quantity: 50,
    total: 79999.5,
    status: "Available",
    image: "https://example.com/laptop-dell-xps-15.jpg",
    action: "Edit",
  },
  {
    product_name: "iPhone 14 Pro",
    category: "Mobile Phones",
    unit_price: 1099.99,
    stock_quantity: 30,
    total: 32999.7,
    status: "Limited Stock",
    image: "https://example.com/iphone-14-pro.jpg",
    action: "Edit",
  },
  {
    product_name: "Sony WH-1000XM4",
    category: "Audio",
    unit_price: 349.99,
    stock_quantity: 0,
    total: 0,
    status: "Out of Stock",
    image: "https://example.com/sony-wh-1000xm4.jpg",
    action: "Edit",
  },
  {
    product_name: "Samsung Galaxy S23",
    category: "Mobile Phones",
    unit_price: 999.99,
    stock_quantity: 40,
    total: 39999.6,
    status: "Available",
    image: "https://example.com/samsung-galaxy-s23.jpg",
    action: "Edit",
  },
  {
    product_name: "MacBook Air M2",
    category: "Computers",
    unit_price: 1299.99,
    stock_quantity: 25,
    total: 32499.75,
    status: "Available",
    image: "https://example.com/macbook-air-m2.jpg",
    action: "Edit",
  },
  {
    product_name: "Logitech MX Master 3S",
    category: "Accessories",
    unit_price: 99.99,
    stock_quantity: 75,
    total: 7499.25,
    status: "Available",
    image: "https://example.com/logitech-mx-master-3s.jpg",
    action: "Edit",
  },
  {
    product_name: "Samsung 32'' 4K Monitor",
    category: "Monitors",
    unit_price: 399.99,
    stock_quantity: 20,
    total: 7999.8,
    status: "Limited Stock",
    image: "https://example.com/samsung-4k-monitor.jpg",
    action: "Edit",
  },
  {
    product_name: "Google Pixel 7",
    category: "Mobile Phones",
    unit_price: 899.99,
    stock_quantity: 35,
    total: 31499.65,
    status: "Available",
    image: "https://example.com/google-pixel-7.jpg",
    action: "Edit",
  },
  {
    product_name: "Apple iPad Pro 12.9",
    category: "Tablets",
    unit_price: 1199.99,
    stock_quantity: 15,
    total: 17999.85,
    status: "Available",
    image: "https://example.com/apple-ipad-pro.jpg",
    action: "Edit",
  },
  {
    product_name: "Bose QuietComfort 45",
    category: "Audio",
    unit_price: 329.99,
    stock_quantity: 60,
    total: 19799.4,
    status: "Available",
    image: "https://example.com/bose-quietcomfort-45.jpg",
    action: "Edit",
  },
];
export { mockProducts };
